In [1]:
import numpy as np

In [2]:
a=np.zeros(5)

In [3]:
a

array([0., 0., 0., 0., 0.])

In [4]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
b=np.zeros((3,4))

In [6]:
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
b.ndim

2

In [8]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [9]:
np.twos(5)

AttributeError: module 'numpy' has no attribute 'twos'

In [10]:
arr=np.zeros((3,4))

In [11]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
arr.ndim

2

In [13]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
arr=np.zeros((3,3,4))

In [15]:
arr

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [16]:
arr.ndim

3

In [18]:
np.zeros((1,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]]])

In [21]:
c=np.zeros((1,1,1,3,3))

In [22]:
c

array([[[[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]]]])

In [23]:
c.ndim

5

In [24]:
arr=np.zeros((3,4))

In [25]:
arr


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
arr+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [27]:
a=arr+5

In [28]:
a**2

array([[25., 25., 25., 25.],
       [25., 25., 25., 25.],
       [25., 25., 25., 25.]])

In [29]:
a


array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [30]:
a-1

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [31]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [32]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
np.eye(3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [35]:
np.empty((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [36]:
import random

In [50]:
random.choice((1,2,3,4,5))

5

In [49]:
random.choice("Ajay")

'a'

In [51]:
random.randrange(1,10)

9

In [52]:
random.random()

0.8455764612882801

In [54]:
lis=[1,2,3,4,5]
lis

[1, 2, 3, 4, 5]

In [56]:
random.shuffle(lis)
lis

[1, 3, 4, 2, 5]

In [58]:
lis

[1, 3, 4, 2, 5]

In [59]:
random.uniform(7,14)

9.97954436273331

In [60]:
np.array([])

array([], dtype=float64)

In [61]:
np.random.random_sample()

0.6909803415193393

In [62]:
np.random.random_sample((5, ))

array([0.15604179, 0.72865709, 0.69622682, 0.46160393, 0.68269779])

In [63]:
np.random.rand(1)

array([0.6715918])

In [66]:
np.random,randn(2, 3)

NameError: name 'randn' is not defined

In [67]:
np.random.randint(1, 5, size=(3,4))

array([[4, 4, 4, 1],
       [2, 4, 1, 2],
       [1, 2, 2, 2]])

In [68]:
arr.reshape(3,4)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [69]:
arr.reshape(4, -1)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [70]:
arr.reshape(4,3,1ṁ)

array([[[0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.]]])

In [72]:
arr1=np.random.randint(1,10,(5,6))


In [73]:
arr1

array([[8, 6, 9, 1, 9, 9],
       [9, 4, 2, 6, 1, 6],
       [8, 1, 2, 9, 5, 8],
       [6, 3, 1, 8, 7, 7],
       [9, 4, 4, 9, 8, 5]])

In [74]:
arr1.shape

(5, 6)

In [75]:
arr.size

12

In [76]:
arr1.ndim

2

In [77]:
arr1

array([[8, 6, 9, 1, 9, 9],
       [9, 4, 2, 6, 1, 6],
       [8, 1, 2, 9, 5, 8],
       [6, 3, 1, 8, 7, 7],
       [9, 4, 4, 9, 8, 5]])

In [78]:
arr1>3

array([[ True,  True,  True, False,  True,  True],
       [ True,  True, False,  True, False,  True],
       [ True, False, False,  True,  True,  True],
       [ True, False, False,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [79]:
arr1[arr1>3]

array([8, 6, 9, 9, 9, 9, 4, 6, 6, 8, 9, 5, 8, 6, 8, 7, 7, 9, 4, 4, 9, 8,
       5])

In [80]:
arr1[arr1>3]

array([8, 6, 9, 9, 9, 9, 4, 6, 6, 8, 9, 5, 8, 6, 8, 7, 7, 9, 4, 4, 9, 8,
       5])

In [81]:
arr1[arr1<3]

array([1, 2, 1, 1, 2, 1])

In [82]:
arr1

array([[8, 6, 9, 1, 9, 9],
       [9, 4, 2, 6, 1, 6],
       [8, 1, 2, 9, 5, 8],
       [6, 3, 1, 8, 7, 7],
       [9, 4, 4, 9, 8, 5]])

In [83]:
arr1[0]

array([8, 6, 9, 1, 9, 9])

In [86]:
arr1[1][2]

np.int64(2)

In [87]:
arr1[3][1]

np.int64(3)

In [89]:
arr1[0]

array([8, 6, 9, 1, 9, 9])

In [90]:
arr1[1][2]

np.int64(2)

In [94]:
arr1=np.random.randint(1,3,(3,3))
arr2=np.random.randint(1,3,(3,3))

In [95]:
arr1

array([[1, 2, 2],
       [1, 1, 2],
       [2, 2, 2]])

In [96]:
arr2

array([[2, 2, 1],
       [2, 1, 2],
       [1, 1, 2]])

In [97]:
arr1+arr2

array([[3, 4, 3],
       [3, 2, 4],
       [3, 3, 4]])

In [98]:
arr1*arr2

array([[2, 4, 2],
       [2, 1, 4],
       [2, 2, 4]])

In [99]:
arr1/arr2

array([[0.5, 1. , 2. ],
       [0.5, 1. , 1. ],
       [2. , 2. , 1. ]])

In [100]:
arr1 // arr2

array([[0, 1, 2],
       [0, 1, 1],
       [2, 2, 1]])

arr1 @ arr2  # matrix multiplicaton of two veriables

In [102]:
np.dot(arr1 , arr2)

array([[ 8,  6,  9],
       [ 6,  5,  7],
       [10,  8, 10]])

In [103]:
arr=np.zeros((3,4))

In [104]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [105]:
a=np.array([[1,2,3,4]])

In [106]:
a

array([[1, 2, 3, 4]])

In [107]:
a.T

array([[1],
       [2],
       [3],
       [4]])