In [1]:
import numpy as np


In [4]:
arr1=np.random.randint(1,3,(3,3))
arr2=np.random.randint(1,3,(3,3))

In [5]:
arr2

array([[1, 1, 1],
       [1, 1, 2],
       [2, 1, 2]])

In [7]:
arr1

array([[2, 2, 1],
       [2, 1, 2],
       [2, 2, 1]])

In [8]:
arr1.flatten()

array([2, 2, 1, 2, 1, 2, 2, 2, 1])

In [10]:
arr=np.array([1,2,3,4])

In [12]:
arr

array([1, 2, 3, 4])

In [13]:
arr.ndim

1

In [14]:
np.expand_dims(arr, axis=0)

array([[1, 2, 3, 4]])

In [15]:
np.expand_dims(arr, axis=1)

array([[1],
       [2],
       [3],
       [4]])

In [17]:
np.expand_dims(arr, axis=1).ndim

2

In [20]:
arr=np.zeros((3,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
np.expand_dims(arr, axis =0)

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [22]:
np.expand_dims(arr, axis =0).ndim

3

In [23]:
np.expand_dims(arr, axis =1)

array([[[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]]])

In [25]:
a=np.array([[1],[2],[3]])

In [26]:
a

array([[1],
       [2],
       [3]])

In [27]:
a.ndim

2

In [29]:
np.squeeze(a)

array([1, 2, 3])

In [30]:
a

array([[1],
       [2],
       [3]])

In [31]:
np.repeat(a,4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [32]:
arr1

array([[2, 2, 1],
       [2, 1, 2],
       [2, 2, 1]])

In [33]:
np.repeat(a, 4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [34]:
arr1

array([[2, 2, 1],
       [2, 1, 2],
       [2, 2, 1]])

In [35]:
np.repeat(arr1,2
          )

array([2, 2, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 1, 1])

In [36]:
np.roll(a, -2)

array([[3],
       [1],
       [2]])

In [37]:
c=np.array([[1,2],[3,4],[5,6],[7,8]])

In [38]:
c

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [40]:
np.roll(c, -1)

array([[2, 3],
       [4, 5],
       [6, 7],
       [8, 1]])

In [41]:
~arr1


array([[-3, -3, -2],
       [-3, -2, -3],
       [-3, -3, -2]])

In [42]:
arr1

array([[2, 2, 1],
       [2, 1, 2],
       [2, 2, 1]])

In [43]:
d=np.array(["pw","skills"])

In [44]:
d

array(['pw', 'skills'], dtype='<U6')

In [45]:
np.char.upper(d)

array(['PW', 'SKILLS'], dtype='<U6')

In [46]:
np.char.capitalize(d)

array(['Pw', 'Skills'], dtype='<U6')

In [ ]:
# mathematical function

In [47]:
arr1

array([[2, 2, 1],
       [2, 1, 2],
       [2, 2, 1]])

In [48]:
np.sin(arr1)

array([[0.90929743, 0.90929743, 0.84147098],
       [0.90929743, 0.84147098, 0.90929743],
       [0.90929743, 0.90929743, 0.84147098]])

In [49]:
np.cos(arr1)

array([[-0.41614684, -0.41614684,  0.54030231],
       [-0.41614684,  0.54030231, -0.41614684],
       [-0.41614684, -0.41614684,  0.54030231]])

In [50]:
np.tan(arr1)

array([[-2.18503986, -2.18503986,  1.55740772],
       [-2.18503986,  1.55740772, -2.18503986],
       [-2.18503986, -2.18503986,  1.55740772]])

In [51]:
np.log10(arr1)

array([[0.30103, 0.30103, 0.     ],
       [0.30103, 0.     , 0.30103],
       [0.30103, 0.30103, 0.     ]])

In [52]:
np.log(arr1)

array([[0.69314718, 0.69314718, 0.        ],
       [0.69314718, 0.        , 0.69314718],
       [0.69314718, 0.69314718, 0.        ]])

In [53]:
np.power(arr1,3)

array([[8, 8, 1],
       [8, 1, 8],
       [8, 8, 1]])

In [54]:
np.max(arr1)

np.int64(2)

In [55]:
arr1

array([[2, 2, 1],
       [2, 1, 2],
       [2, 2, 1]])

In [56]:
np.mean(arr1)

np.float64(1.6666666666666667)

In [57]:
np.min(arr1)

np.int64(1)

In [60]:
np.std(arr1)

np.float64(0.4714045207910317)

In [61]:
np.var(arr1)

np.float64(0.2222222222222222)

In [62]:
np.subtract(arr1,arr2)

array([[ 1,  1,  0],
       [ 1,  0,  0],
       [ 0,  1, -1]])

In [64]:
np.mod(arr1, arr2)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 1]])

In [65]:
import numpy.matlib as nm


In [66]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
# numpy linear algebra


In [67]:
arr1

array([[2, 2, 1],
       [2, 1, 2],
       [2, 2, 1]])

In [68]:
arr2

array([[1, 1, 1],
       [1, 1, 2],
       [2, 1, 2]])

In [69]:
arr1 @ arr2

array([[6, 5, 8],
       [7, 5, 8],
       [6, 5, 8]])

In [70]:
np.linalg.det(arr1)

np.float64(0.0)

In [71]:
np.linalg.det(arr2)

np.float64(1.0)

In [72]:
np.linalg.inv(arr2)

array([[ 0., -1.,  1.],
       [ 2.,  0., -1.],
       [-1.,  1., -0.]])

In [75]:
a=np.array([[7,5.3,-3],[3,-5,2],[5,3,-7]])

In [76]:

a

array([[ 7. ,  5.3, -3. ],
       [ 3. , -5. ,  2. ],
       [ 5. ,  3. , -7. ]])

In [77]:
b=np.array([16,8,0])

In [78]:
np.linalg.solve(a,b)

array([2.59630607, 0.84432718, 2.21635884])