In [4]:
import numpy as np


In [5]:
np.__version__

'2.0.2'

In [6]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [7]:
lis=[1,2,3,"pwskills",3+5j,True,1.2]
type(lis)

list

In [8]:
l=[1,2,3,4,5]
type(l)

list

In [10]:
arr=np.array(l)
type(arr)

numpy.ndarray

In [11]:
arr

array([1, 2, 3, 4, 5])

In [12]:
l=[1,2,3,4,5,"sanjay"]
np.array(l)

array(['1', '2', '3', '4', '5', 'sanjay'], dtype='<U21')

In [23]:
aar1=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
aar1

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [24]:
aar1.ndim

3

In [15]:
mat=np.matrix([1,2,3,4])

In [16]:
type[mat]

type[matrix([[1, 2, 3, 4]])]

In [17]:
type(mat)

numpy.matrix

In [18]:
mat.ndim

2

In [19]:
mat

matrix([[1, 2, 3, 4]])

In [21]:
np.matrix([[[1,2,3],[3,4,3],[5,6,3]]])

ValueError: matrix must be 2-dimensional

In [26]:
l=[1,2,3]
np.asarray(l)

array([1, 2, 3])

In [27]:
np.asanyarray(l)

array([1, 2, 3])

In [28]:
t=([1,2,3],[4,5,6])
type(t)

tuple

In [30]:
np.array(t)

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
aar



NameError: name 'aar' is not defined

In [34]:
arr=np.array(t)


In [35]:
arr


array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
arr[0]

array([1, 2, 3])

In [39]:
arr[0]=([4,4,4])

In [40]:
t

([1, 2, 3], [4, 5, 6])

In [41]:
a

NameError: name 'a' is not defined

In [42]:
arr.shape


(2, 3)

In [43]:
arr.size

6

In [44]:
iterator=(i for i in range(5))

In [45]:
iterator

<generator object <genexpr> at 0x7f6d357cfe80>

In [46]:
np.fromiter(iterator, float)

array([0., 1., 2., 3., 4.])

In [47]:
np.fromstring('22 23 24', sep=" ")

array([22., 23., 24.])

In [48]:
np.fromstring('22 23 24', sep=" ", dtype=int)

array([22, 23, 24])

In [49]:
string="rajesh khana tripti chavan"

In [52]:
string.split(" ")

['rajesh', 'khana', 'tripti', 'chavan']

In [53]:
np.array(string.split(" "))

array(['rajesh', 'khana', 'tripti', 'chavan'], dtype='<U6')

In [54]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [55]:
range(10)

range(0, 10)

In [57]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [58]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [59]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])